FROM python:3.9-slim

WORKDIR /app

# Установка зависимостей
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код агента
COPY . .

EXPOSE 8000

# Изменённая команда для запуска Streamlit
CMD ["streamlit", "run", "main.py", "--server.port=8000", "--server.address=0.0.0.0"]